using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections;

namespace OrbitzExportStaticFile
{
    public class AmenityCode
    {
        Hashtable amenityCodeList = new Hashtable();

        public Hashtable getAmenitiesCodeList
        {
            get { return this.amenityCodeList; }
        }
 
        public AmenityCode()
        {
            amenityCodeList.Add("ORBGYM", "Fitness Room");
            amenityCodeList.Add("BUSCTR", "Business Center");
            amenityCodeList.Add("CNFFAC", "Conference Facilities");
            amenityCodeList.Add("CONLEV", "Concierge");
            amenityCodeList.Add("DISABL", "Handicapped Rooms/Facilities");
            amenityCodeList.Add("HEALTH", "Health Club");
            amenityCodeList.Add("PETS", "Pets Allowed");
            amenityCodeList.Add("POOL", "Pool");
            amenityCodeList.Add("REST", "Restaurant");
            amenityCodeList.Add("ROOM", "Room Service");
            amenityCodeList.Add("AC120", "120 AC");
            amenityCodeList.Add("DC120", "120 DC");
            amenityCodeList.Add("DC220", "220 DC");
            amenityCodeList.Add("AC220", "220 AC");
            amenityCodeList.Add("ADJNG", "Adjoining Rooms");
            amenityCodeList.Add("ADPTRS", "Outlet Adapters");
            amenityCodeList.Add("AIRCON", "Air Conditioned");
            amenityCodeList.Add("AIRLIN", "Airline Desk");
            amenityCodeList.Add("ALRMCK", "AM/FM Alarm Clock");
            amenityCodeList.Add("ANNEX", "Annex Room");
            amenityCodeList.Add("AP", "Meal Plan - American");
            amenityCodeList.Add("AVEQUP", "Audio Visual Equipment");
            amenityCodeList.Add("BABY", "Babysitting/Child Services");
            amenityCodeList.Add("BALCON", "Balcony");
            amenityCodeList.Add("BAR", "Bar/Lounge");
            amenityCodeList.Add("BARBER", "Barber Shop");
            amenityCodeList.Add("BATH", "Bath Tub");
            amenityCodeList.Add("BAY", "On The Bay");
            amenityCodeList.Add("BAYVW", "Bay View");
            amenityCodeList.Add("BB", "Meal Plan - Bed and Breakfast");
            amenityCodeList.Add("BBYLSN", "Baby Listening Device");
            amenityCodeList.Add("BCHVW", "Beach View");
            amenityCodeList.Add("BEACH", "Beach");
            amenityCodeList.Add("BEAUTY", "Barber/Beauty Shop");
            amenityCodeList.Add("BELL", "Porters");
            amenityCodeList.Add("BIDET", "Bidet");
            amenityCodeList.Add("BLKBRD", "Blackboard");
            amenityCodeList.Add("BOATNG", "Boating");
            amenityCodeList.Add("BOUTIQ", "Boutiques");
            amenityCodeList.Add("BOWLIN", "Bowling");
            amenityCodeList.Add("BP", "Meal Plan - Bermuda");
            amenityCodeList.Add("BRKFST", "Breakfast");
            amenityCodeList.Add("BTHTEL", "Bathroom Telephone");
            amenityCodeList.Add("CANOPY", "Canopy / Poster Bed");
            amenityCodeList.Add("CAR", "Car Rental Desk");
            amenityCodeList.Add("CASINO", "Casino");
            amenityCodeList.Add("CASTLE", "Castle Room");
            amenityCodeList.Add("CB", "Meal Plan - Caribbean");
            amenityCodeList.Add("CELTEL", "Cellular Telephone Rental");
            amenityCodeList.Add("CITYVW", "City View");
            amenityCodeList.Add("CMPRTL", "Computer Rental");
            amenityCodeList.Add("CNFSTE", "Conference Suite");
            amenityCodeList.Add("CNTBRK", "Continental Breakfast");
            amenityCodeList.Add("COFFEE", "Coffee Shop");
            amenityCodeList.Add("COFMKR", "Coffee Maker in Room");
            amenityCodeList.Add("COMPUT", "Computer in Room");
            amenityCodeList.Add("CONDSK", "Concierge Desk");
            amenityCodeList.Add("CONN", "Connecting Rooms");
            amenityCodeList.Add("CP", "Meal Plan - Continental");
            amenityCodeList.Add("CPSVC", "Copy Service");
            amenityCodeList.Add("CRDTEL", "Cordless Phone");
            amenityCodeList.Add("CRIB", "Cribs Available");
            amenityCodeList.Add("CRTYRD", "Courtyard");
            amenityCodeList.Add("CURREX", "Currency Exchange");
            amenityCodeList.Add("DESK24", "24 Hour Front Desk");
            amenityCodeList.Add("DINEGD", "Dining Guide");
            amenityCodeList.Add("DINNER", "Dinner");
            amenityCodeList.Add("DISCO", "Disco");
            amenityCodeList.Add("DOCTOR", "Doctor on Call");
            amenityCodeList.Add("DOORMN", "Doorman");
            amenityCodeList.Add("DOUBLE", "Double Bed");
            amenityCodeList.Add("DOWN", "Downstairs");
            amenityCodeList.Add("DRGSTR", "Drugstore");
            amenityCodeList.Add("DRVRNG", "Driving Range");
            amenityCodeList.Add("DTYFRE", "Duty Free Shop");
            amenityCodeList.Add("DWNIN", "Down and In Room");
            amenityCodeList.Add("DWNOUT", "Down and Out Room");
            amenityCodeList.Add("EASEL", "Easel");
            amenityCodeList.Add("EFFCY", "Efficiency");
            amenityCodeList.Add("ELEV", "Elevators");
            amenityCodeList.Add("ENTMNT", "Live Entertainment");
            amenityCodeList.Add("EP", "Meal Plan - European");
            amenityCodeList.Add("EXCKIN", "Express Check In");
            amenityCodeList.Add("EXCKOT", "Express Checkout");
            amenityCodeList.Add("EXDESK", "Executive Desk");
            amenityCodeList.Add("EXLEVL", "Executive Level");
            amenityCodeList.Add("FAMILY", "Family Plan");
            amenityCodeList.Add("FAP", "Meal Plan - FAP/Full-board");
            amenityCodeList.Add("FAX", "FAX");
            amenityCodeList.Add("FEMEX", "Female Executive Rooms");
            amenityCodeList.Add("FIRELT", "Fire Alarm with Light");
            amenityCodeList.Add("FIREPL", "Fire Place");
            amenityCodeList.Add("FISH", "Fishing");
            amenityCodeList.Add("FLORST", "Florist");
            amenityCodeList.Add("FPRKNG", "Free Parking");
            amenityCodeList.Add("FTRANS", "Free Transportation");
            amenityCodeList.Add("GAME", "Game Room");
            amenityCodeList.Add("GARDEN", "On the Garden");
            amenityCodeList.Add("GARDVW", "Garden View");
            amenityCodeList.Add("GIFT", "Gift Shop");
            amenityCodeList.Add("GOLF", "Golf");
            amenityCodeList.Add("GOLFVW", "Golf Course View");
            amenityCodeList.Add("NSMK", "No Smoking Rooms/Facilities");
            amenityCodeList.Add("GRABBR", "Grab Bars in Bathroom");
            amenityCodeList.Add("GRECTB", "Grecian Tub");
            amenityCodeList.Add("GRNARY", "Granary Room");
            amenityCodeList.Add("GYM", "Exercise Gym");
            amenityCodeList.Add("HAIR", "Hairdryer in Room");
            amenityCodeList.Add("HEAT", "Heated Guest Rooms");
            amenityCodeList.Add("HNYSTE", "Honeymoon Suite");
            amenityCodeList.Add("HORSE", "Horseback Riding");
            amenityCodeList.Add("ICEMCH", "Ice Machine");
            amenityCodeList.Add("IDD", "International Direct Dial");
            amenityCodeList.Add("IRON", "Iron");
            amenityCodeList.Add("IRONBD", "Ironing Board");
            amenityCodeList.Add("JACUZ", "Jacuzzi");
            amenityCodeList.Add("JOGTRK", "Jogging Track");
            amenityCodeList.Add("KENNEL", "Kennels");
            amenityCodeList.Add("KING", "King Bed");
            amenityCodeList.Add("KITETT", "Kitchenette");
            amenityCodeList.Add("KITFUL", "Kitchen");
            amenityCodeList.Add("LAKE", "On the Lake");
            amenityCodeList.Add("LAKEVW", "Lake View");
            amenityCodeList.Add("LANAI", "Lanai");
            amenityCodeList.Add("LDRYMT", "Guest Laundromat");
            amenityCodeList.Add("LOFT", "Loft");
            amenityCodeList.Add("LOUNGE", "Lounge");
            amenityCodeList.Add("LUNCH", "Lunch");
            amenityCodeList.Add("MADSVC", "Maid Service");
            amenityCodeList.Add("MAP", "Meal Plan - MAP/Half-board");
            amenityCodeList.Add("MARINA", "On the Marina");
            amenityCodeList.Add("MARNVW", "Marina View");
            amenityCodeList.Add("MDMRM", "Modem in Room");
            amenityCodeList.Add("MICRWV", "Microwave");
            amenityCodeList.Add("MINBAR", "Mini Bar");
            amenityCodeList.Add("MINGLF", "Miniature Golf");
            amenityCodeList.Add("MODEM", "Modem Lines in Room");
            amenityCodeList.Add("MOVIES", "In Room Movies");
            amenityCodeList.Add("MP", "Meal Plan");
            amenityCodeList.Add("MTGFAC", "Meeting/Banquet Facilities");
            amenityCodeList.Add("MTGSTE", "Meeting Suite");
            amenityCodeList.Add("MTNVW", "Mountain View");
            amenityCodeList.Add("MULTI", "Multilingual");
            amenityCodeList.Add("MURPHY", "Murphy Bed");
            amenityCodeList.Add("NRSERY", "Nursery for Children");
            amenityCodeList.Add("NTECLB", "Night Club");
            amenityCodeList.Add("NWSPPR", "Free Newspaper");
            amenityCodeList.Add("NWSSTD", "News Stand");
            amenityCodeList.Add("OCEAN", "On the Ocean");
            amenityCodeList.Add("OCNVW", "Ocean View");
            amenityCodeList.Add("OVRPRJ", "Overhead Projector");
            amenityCodeList.Add("OVRSZD", "Over Sized Rooms");
            amenityCodeList.Add("PARK", "On the Park");
            amenityCodeList.Add("PARKVW", "Park View");
            amenityCodeList.Add("PARLOR", "Parlor");
            amenityCodeList.Add("PASYSM", "Public Address System");
            amenityCodeList.Add("PHNSRV", "Phone Service");
            amenityCodeList.Add("PICNIC", "Picnic Area/Tables");
            amenityCodeList.Add("PLYGRD", "Play Ground");
            amenityCodeList.Add("POOLHT", "Heated Pool");
            amenityCodeList.Add("POOLIN", "Indoor Pool");
            amenityCodeList.Add("POOLOT", "Outdoor Pool");
            amenityCodeList.Add("POOLSB", "Poolside Snackbar");
            amenityCodeList.Add("POOLSD", "Poolside Room");
            amenityCodeList.Add("POOLVW", "Pool View");
            amenityCodeList.Add("PRJECT", "Projector");
            amenityCodeList.Add("PRKBUS", "Bus Parking");
            amenityCodeList.Add("PRKIND", "Indoor Parking");
            amenityCodeList.Add("PRKNG", "Parking");
            amenityCodeList.Add("PRKOUT", "Outdoor Parking");
            amenityCodeList.Add("PRKRV", "RV or Truck Parking");
            amenityCodeList.Add("PRKTRK", "Truck Parking");
            amenityCodeList.Add("PRKVAL", "Valet Parking");
            amenityCodeList.Add("PRYRMT", "Prayer Mats");
            amenityCodeList.Add("PUTGRN", "Putting Green");
            amenityCodeList.Add("QUEEN", "Queen Bed");
            amenityCodeList.Add("RACCRT", "Racquetball Courts");
            amenityCodeList.Add("RADIO", "Radio");
            amenityCodeList.Add("RECLNR", "Recliner");
            amenityCodeList.Add("REFRIG", "Refrigerator");
            amenityCodeList.Add("RIVER", "On the River");
            amenityCodeList.Add("RIVVW", "River View");
            amenityCodeList.Add("RLWY", "Rollaway Beds");
            amenityCodeList.Add("ROOM24", "24 Hour Room Service");
            amenityCodeList.Add("ROOMOR", "Oriental Room Style");
            amenityCodeList.Add("ROOMWE", "Western Room Style");
            amenityCodeList.Add("SAFDEP", "Safe Deposit Box");
            amenityCodeList.Add("SAFE", "Safe");
            amenityCodeList.Add("SAUNA", "Sauna");
            amenityCodeList.Add("SCUBA", "Scuba Diving");
            amenityCodeList.Add("SECSVC", "Secretarial Service");
            amenityCodeList.Add("SECU24", "24 Hour Security");
            amenityCodeList.Add("SECURE", "Security");
            amenityCodeList.Add("SHOWER", "Shower");
            amenityCodeList.Add("SHPMAL", "Shopping Mall");
            amenityCodeList.Add("SHUTTL", "Free Airport Shuttle");
            amenityCodeList.Add("SICO", "Sico Bed");
            amenityCodeList.Add("SINGLE", "Single Bed");
            amenityCodeList.Add("SITTNG", "Sitting Area");
            amenityCodeList.Add("SKEET", "Skeet Shooting");
            amenityCodeList.Add("SKIING", "Skiing");
            amenityCodeList.Add("SKIXC", "Cross Country Skiing");
            amenityCodeList.Add("SLOPVW", "Slope View");
            amenityCodeList.Add("SMKDET", "Smoke Detectors");
            amenityCodeList.Add("SOFABD", "Sofa Bed");
            amenityCodeList.Add("SOLARM", "Solarium");
            amenityCodeList.Add("SPA", "Fitness Center or Spa");
            amenityCodeList.Add("SPORTS", "Sports Available");
            amenityCodeList.Add("SPRINK", "Sprinklers In Rooms");
            amenityCodeList.Add("STMBTH", "Steam Bath");
            amenityCodeList.Add("SUITE", "Suite");
            amenityCodeList.Add("TDDTEL", "TDD Telephone Machine");
            amenityCodeList.Add("TEL", "Telephone");
            amenityCodeList.Add("TELEX", "Telex");
            amenityCodeList.Add("TENIN", "Indoor Tennis");
            amenityCodeList.Add("TENOUT", "Outdoor Tennis");
            amenityCodeList.Add("TENPRO", "Tennis Pro");
            amenityCodeList.Add("TERACE", "Terrace");
            amenityCodeList.Add("THEATR", "Theater Desk");
            amenityCodeList.Add("THEMRM", "Theme Room");
            amenityCodeList.Add("TMPCTL", "Temperature Control");
            amenityCodeList.Add("TOILET", "Toilet");
            amenityCodeList.Add("TOUR", "Tour Desk");
            amenityCodeList.Add("TOWER", "Tower Room");
            amenityCodeList.Add("TPRCDR", "Tape Recorder");
            amenityCodeList.Add("TRNDWN", "Turndown Service");
            amenityCodeList.Add("TV", "TV");
            amenityCodeList.Add("TVCAB", "Television with Cable");
            amenityCodeList.Add("TVRMOT", "TV Remote Control");
            amenityCodeList.Add("TWIN", "Twin Bed");
            amenityCodeList.Add("UPSTRS", "Upstairs");
            amenityCodeList.Add("VALET", "Laundry/Valet Services");
            amenityCodeList.Add("VALTCG", "Vaulted Ceiling");
            amenityCodeList.Add("VCR", "VCR");
            amenityCodeList.Add("VENDNG", "Vending Machines");
            amenityCodeList.Add("VIDEO", "Video Tapes");
            amenityCodeList.Add("VILLA", "Villa");
            amenityCodeList.Add("VIP", "VIP Rooms/Services");
            amenityCodeList.Add("WAKEUP", "Wake-up Service");
            amenityCodeList.Add("WC", "WC");
            amenityCodeList.Add("WETBAR", "Wet Bar");
            amenityCodeList.Add("WHTBRD", "White Board");
            amenityCodeList.Add("WNDSRF", "Wind Surfing");
            amenityCodeList.Add("WTRBD", "Waterbed");
            amenityCodeList.Add("WTRSKI", "Water Skiing");
            amenityCodeList.Add("FRCLLS", "Free Local Telephone Calls");
            amenityCodeList.Add("CTSCAR", "Courtesy Car");
            amenityCodeList.Add("SHOP", "Shops/Commercial Services");
            amenityCodeList.Add("TENNIS", "Tennis");
            amenityCodeList.Add("LANDRY", "Laundry Service");
            amenityCodeList.Add("CTYCTR", "City Center");
            amenityCodeList.Add("HSTCTY", "Historic City");
            amenityCodeList.Add("ATM", "ATM/Cash Machine");
            amenityCodeList.Add("BRKBUF", "Breakfast Buffet");
            amenityCodeList.Add("CDPLYR", "CD Player");
            amenityCodeList.Add("DATAPT", "Data port Available");
            amenityCodeList.Add("DSKLMP", "Desk with Lamp");
            amenityCodeList.Add("DVD", "DVD Player");
            amenityCodeList.Add("ELECDR", "Electronic Door Locks");
            amenityCodeList.Add("EMAIL", "Email Service");
            amenityCodeList.Add("EXSTAY", "Extended Stay");
            amenityCodeList.Add("FEMA", "FEMA Approved");
            amenityCodeList.Add("GMPLYR", "Video Game Player");
            amenityCodeList.Add("INTHS", "High Speed Internet");
            amenityCodeList.Add("INTRNT", "Internet Access");
            amenityCodeList.Add("KIDACT", "Children Activities");
            amenityCodeList.Add("MOUNT", "Mountain");
            amenityCodeList.Add("PETNO", "No Pets Allowed");
            amenityCodeList.Add("PHDATA", "Phone with data port");
            amenityCodeList.Add("PHSPKR", "Phone with speaker");
            amenityCodeList.Add("RURAL", "Rural/Country");
            amenityCodeList.Add("STEKID", "Children Suite");
            amenityCodeList.Add("TPRESS", "Trouser Press");
            amenityCodeList.Add("TVSAT", "Satellite TV");
            amenityCodeList.Add("VIDCKO", "Video Checkout");
            amenityCodeList.Add("ORBBRK", "Free Breakfast");
            amenityCodeList.Add("ORBSHT", "Airport Shuttle");
            amenityCodeList.Add("ORBSPA", "Spa Services");
            amenityCodeList.Add("ORBWLS", "Wireless Internet");
            amenityCodeList.Add("OTA_P_212", "ATM");
            amenityCodeList.Add("OTA_P_217", "Children not allowed");
            amenityCodeList.Add("OTA_P_903", "Smoke-free policy");
            amenityCodeList.Add("SMOKING", "Smoking");
            amenityCodeList.Add("HALFBOARD", "Half board");
            amenityCodeList.Add("HALF_BOARD", "Half board");
            amenityCodeList.Add("FULL_BOARD", "Full board");
            amenityCodeList.Add("BREAKFAST_BOARD", "Breakfast board");
            amenityCodeList.Add("FOOD_WINE", "Food and wine");
            amenityCodeList.Add("HAMMOCK", "Hammock");
            amenityCodeList.Add("GOLF_PACKAGE", "Golf package");
            amenityCodeList.Add("DOUBLE_JACUZZI", "Double Jacuzzi");
            amenityCodeList.Add("CONCIERGE", "Concierge");
            amenityCodeList.Add("BREAK_FAST", "Breakfast");
            amenityCodeList.Add("CONTINENTAL_BREAKFAST", "Continental breakfast");
            amenityCodeList.Add("BUFFET_BREAK", "Buffet breakfast");
            amenityCodeList.Add("SHARED_LOUNGE", "Shared lounge");
            amenityCodeList.Add("SHARED_KITCHEN", "Shared kitchen");
            amenityCodeList.Add("FREE_PARKING", "Free parking");
            amenityCodeList.Add("WATER_PARK", "Water park passes");
            amenityCodeList.Add("SHARED_IN_BATHROOM", "Shared In-room bathroom");
            amenityCodeList.Add("VERANDAH", "Verandah");
            amenityCodeList.Add("HOUSE_KEEPING", "Housekeeping");
            amenityCodeList.Add("NO_HOUSE_KEEPING", "No Housekeeping");
            amenityCodeList.Add("BROBE", "Bathrobe");
            amenityCodeList.Add("BTHAM", "Bathroom Amenities");
            amenityCodeList.Add("VMAIL", "Voicemail");
            amenityCodeList.Add("SHBTH", "Shared Bathroom");
            amenityCodeList.Add("FLTSCR", "Flatscreen");
            amenityCodeList.Add("WRDSK", "Writing Desk");
            amenityCodeList.Add("CHDCR", "Child Care");
            amenityCodeList.Add("CPLYRM", "Children Playroom");
            amenityCodeList.Add("PRKCST", "Parking Facilities at Cost");
            amenityCodeList.Add("CPOOL", "Childrens Swimming Pool");
            amenityCodeList.Add("BLLRM", "Ball Room");
            amenityCodeList.Add("BBQAR", "Barbecue Area");
            amenityCodeList.Add("GRDNAR", "Garden");
            amenityCodeList.Add("DINRM", "Dinning Room");
            amenityCodeList.Add("LIB", "Library");
            amenityCodeList.Add("TTEN", "Table Tennis");
            amenityCodeList.Add("BLRDS", "Billiards");
            amenityCodeList.Add("BSKTBAL", "Basket Ball Court");
            amenityCodeList.Add("RCPTN", "Reception");
            amenityCodeList.Add("LOBBY", "Lobby");
            amenityCodeList.Add("PLNGPL", "Plunge Pool");
            amenityCodeList.Add("HAC47", "Accessible facilities");
            amenityCodeList.Add("PHY50", "Handicapped parking");
            amenityCodeList.Add("HAC116", "Accessible parking");
            amenityCodeList.Add("PHY2", "Audible emergency alarm for sight impaired guest");
            amenityCodeList.Add("PHY34", "Visual emergency alarm for hearing impaired guest");
            amenityCodeList.Add("PHY69", "Service dogs allowed");
            amenityCodeList.Add("PHY28", "Public areas wheelchair accessible for disabled");
            amenityCodeList.Add("PHY29", "Service animals allowed");
            amenityCodeList.Add("PHY42", "Wheelchair accessible elevators");
            amenityCodeList.Add("RMA161", "Accessible rooms");
            amenityCodeList.Add("KNCKLT", "Knock Light (Hearing Impaired)");
            amenityCodeList.Add("ADA", "Americans with Disabilities Act (ADA) compliance");
            amenityCodeList.Add("BRALEL", "Brailled Elevators");
            amenityCodeList.Add("RMPACC", "Ramp Access to Buildings");
            amenityCodeList.Add("WCHR", "Wheel Chair Access");
            amenityCodeList.Add("HAC179", "Wireless Internet in Public Areas");
            amenityCodeList.Add("HAC261", "Wi-Fi");
            amenityCodeList.Add("HAC222", "FREE Internet");
            amenityCodeList.Add("RMA207", "FREE Internet in Room");
            amenityCodeList.Add("HAC138", "FREE Buffet Breakfast");
            amenityCodeList.Add("HAC141", "FREE Continental Breakfast");
            amenityCodeList.Add("HAC142", "FREE Full Breakfast");
            amenityCodeList.Add("HAC156", "All Inclusive");		
        }
    }
}
